### ISSUE TITLE
Feature request - Cancel zipping files into nw.exe

### ISSUE THREAD

**Issue by avihaymenahem** [nwjs/nw-builder#164]
As for now, the nwb zipping the whole files into one directory,this is a huge problem for me when i've got more than 25 node modules included which i dont need them all on startup.

I think that in option something like: ``` zip : false ``` should be allowed in order to cancel the zipping of whole files into one huge one.

Thanks :)

**Comment by cbabos** [comment]
Actually I think the best solution for this problem is to modify your workflow. The builder's task is to create the final build so I think it's not a very good feature to request "please not build that" from it :)
This is how I'm using it: 
 I have an app and a dist folder. My build task (I'm using `generator-gulp-webapp`) run some linting, compressing etc. (so it builds the HTML5, CSS, JS parts of the app), and put the builded webapp to the dist folder. After that, I've run the nwb on the dist folder, so the final `.exe(win)|.app(osx)` build contains only the production version of the code.

**Comment by avihaymenahem** [comment]
You need the node modules only for development, i need most of them for production....

**Comment by cbabos** [comment]
@avihaymenahem then this was a misunderstanding from me. Sorry :)

**Comment by avihaymenahem** [comment]
@mllrsohn Can i get at least any direction so i can code it myself? :)

**Comment by felicienfrancois** [comment]
@avihaymenahem This option already exists for mac distribution (`macZip`) so you can have a look at how and where the switch is implemented by searching macZip in the code.

**Comment by 1j01** [comment]
https://github.com/mllrsohn/node-webkit-builder/pull/193?

**Comment by adam-lynch** [comment]
Is #193 what you want? How does it compare to #200? 

cc @CamiloMM, @kessler, @felicienfrancois, @speedskater, @KalleV

**Comment by speedskater** [comment]
Imho #193 is a different option. As far as i understood, #193 adds an option which allows to disable the merging of the zip file into the executable. #200 does not zip the application at all and therefore the application will not be extracted on startup.

**Comment by matthew-dean** [comment]
What about addressing this with something like asar? - https://github.com/atom/asar

**Comment by adam-lynch** [comment]
Released in 2.2.0. Thanks everyone!
