### ISSUE TITLE
Utils.copyFile not resolving with anything

### ISSUE THREAD

**Issue by chrisronline** [nwjs/nw-builder#181]
Hi,

It looks like the ```copyFile``` method correctly resolves a promise when the copy is complete, but fails to pass in any useful data causing ```mergeAppFile``` to return an array of undefined which propagates to ```build``` and my calling code.

Path:
[copyFile](https://github.com/mllrsohn/node-webkit-builder/blob/master/lib/utils.js#L99)
[mergeAppFiles](https://github.com/mllrsohn/node-webkit-builder/blob/master/lib/index.js#L440)
[build](https://github.com/mllrsohn/node-webkit-builder/blob/master/lib/index.js#L101)

On this subject, ideally ```info``` contains information about the directory structure created and what files were created.

I can open a PR, but unsure your thoughts for this ```info``` variable.

Thanks

**Comment by adam-lynch** [comment]
To be honest I'm not familiar with this. I wonder what this was doing originally. So should `info` be in your opinion? An array of path strings?

**Comment by shennan** [comment]
This sounds like it might be part of an issue I'm having. I get the following when building an OSX application on Windows:
```
Using cache for: osx32
Create release folder in C:\path\to\AppName\osx32
chmod 33206 on C:\path\to\AppName\osx32\AppName.app\Contents\Resources\nw.icns failed after copying, ignoring
{ [ Error: EPERM, operation not permitted 'C:\path\to\AppName\osx\AppName.app']
  errno: 50,
  code: 'EPERM',
  path: 'C:\\path\\to\\AppName\\osx32\\AppName.app',
  syscall: 'rename' }
```

The application bundles fine, but when it tries to do any of the icon stuff, it chokes with the above error. It's worth noting that the build sometimes succeeds, and sometimes fails. A fail is pretty inevitable when batch-building though.

Does this sound like it could be caused by this issue @chrisronline?

**Comment by adam-lynch** [comment]
@shennan I don't see the connection, besides the fact that it involves copying too. I think you're having problems which we've been struggling with for a few versions now (look at other issues). Make sure you've the latest version, it's much better now but not 100% fixed.

**Comment by shennan** [comment]
@adam-lynch You may be right. However, the other issues have not yet had the exact same error (EPERM 50). Also, what is strange is that it has only started failing in this way recently (within the last couple of days). I have been using latest webkit-node-builder, and have rolled back to 1.0.6 with the same result.

I just figured this might be related since the error is thrown round about [this line](https://github.com/mllrsohn/node-webkit-builder/blob/master/lib/utils.js#L96) in `utils.js`.

Which other issues do you think are relevant to this so I can have a good read and try and chip-in with a solution?

**Comment by adam-lynch** [comment]
@shennan I'm thinking this is more to do with one of the following: #142 #144 #148 #170 #180

**Comment by chrisronline** [comment]
I'm not sure @adam-lynch - I'm just hoping for some path information about where the built files live so I can use that in later build steps
