### ISSUE TITLE
help with command line to build the executable file

### ISSUE THREAD

**Issue by LOL2011** [nwjs/nw-builder#349]
I'm not great with command line stuff and am really struggling getting this working. Can anyone help me figure out exactly what I need to do to build the execution file for my app?

I have installed nw-builder.

I have two folders,  one containing the app files and the package.json, the other folder containing all the NW files.    I have also created a third folder that merges the these two folders and where I have changed the .zip file of the app to a .nw file.

Where do I run the buildDir command from?

and what would the exact command be?

Is it:
nwbuild --buildDir /build

or:
nwbuild -o, --buildDir /build

Many thanks in advance!

**Comment by adam-lynch** [comment]
OK I'll help but keep in mind I personally don't use the CLI interface 😄 . So what you have in the end is an `.nw` file yeah? I'm not sure if that's supported by nw-builder, I could be wrong. You might need to have a directory instead of a zip / `.nw` (like https://github.com/nwjs/nw-builder/tree/master/example/nwapp) and run a command like the following from inside that directory:

```shell
nwbuild --platforms win64, osx64 
```

The `buildDir` option defaults to `./build` so you should see your generated executables in a `build` directory in the directory where you ran the command.

I hope that helps. If that doesn't work, let me know and we'll investigate.

**Comment by LOL2011** [comment]
Thank you so much for your response.  Sorry for the delay in responding, I have been away. Unfortunately it didn't work.  I get, "Error: unknown platform"
